//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCV
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGPHANCONG
    {
        public DANGPHANCONG()
        {
            this.PHANCONGs = new HashSet<PHANCONG>();
        }
    
        public int ID { get; set; }
        public string TEN { get; set; }
    
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
    }
}
