//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCVEntities : DbContext
    {
        public QLCVEntities()
            : base("name=QLCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BAOCAOCONGVIEC> BAOCAOCONGVIECs { get; set; }
        public DbSet<BINHLUAN> BINHLUANs { get; set; }
        public DbSet<CHUCDANH> CHUCDANHs { get; set; }
        public DbSet<CHUCVU> CHUCVUs { get; set; }
        public DbSet<CONGVIEC> CONGVIECs { get; set; }
        public DbSet<DANGCONGVIEC> DANGCONGVIECs { get; set; }
        public DbSet<DANGPHANCONG> DANGPHANCONGs { get; set; }
        public DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public DbSet<PHANCONG> PHANCONGs { get; set; }
        public DbSet<PHONGBAN> PHONGBANs { get; set; }
        public DbSet<TRANGTHAI> TRANGTHAIs { get; set; }
    }
}
