//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCV
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public NGUOIDUNG()
        {
            this.BAOCAOCONGVIECs = new HashSet<BAOCAOCONGVIEC>();
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.CONGVIECs = new HashSet<CONGVIEC>();
            this.PHANCONGs = new HashSet<PHANCONG>();
        }
    
        public int ID { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string TENNGUOIDUNG { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> IDPHONGBAN { get; set; }
        public Nullable<int> IDCHUCDANH { get; set; }
        public Nullable<int> IDCHUCVU { get; set; }
    
        public virtual ICollection<BAOCAOCONGVIEC> BAOCAOCONGVIECs { get; set; }
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        public virtual CHUCDANH CHUCDANH { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual ICollection<CONGVIEC> CONGVIECs { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
    }
}
