//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCV
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG
    {
        public int IDPHANCONG { get; set; }
        public int IDNGUOINHAN { get; set; }
        public int IDCONGVIEC { get; set; }
        public string TENPHANCONG { get; set; }
        public Nullable<int> IDTRANGTHAI { get; set; }
        public Nullable<int> IDDANGPHANCONG { get; set; }
        public string NOIDUNG { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
    
        public virtual CONGVIEC CONGVIEC { get; set; }
        public virtual DANGPHANCONG DANGPHANCONG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual TRANGTHAI TRANGTHAI { get; set; }
    }
}
